import assert from "node:assert/strict";
import { buildDeck, dayKey, emptyProgress, ensureSession, parseProgress, rateCard, recordPresentation } from "../app/review-engine.mjs";
import { readFile } from "node:fs/promises";

const notes = JSON.parse(await readFile(new URL("../data/hmi-notes.json", import.meta.url)));
const deck = buildDeck(notes);
assert.equal(new Set(deck.map(card => card.id)).size, deck.length);
assert(deck.every(card => card.text && card.answer));
const now = new Date("2026-09-05T08:00:00+08:00");
assert.equal(dayKey(new Date("2026-09-05T16:00:00Z")), "2026-09-06");
const data = emptyProgress();
let session = ensureSession(data, deck, "word", now);
assert.equal(session.queue.length, 8);
const first = session.queue[0];
recordPresentation(data, "word", now);
recordPresentation(data, "word", now);
assert.equal(data.stats[first].shown, 1);
rateCard(data, "word", "forgot", now);
assert.equal(data.stats[first].forgot, 1);
assert.equal(session.queue[2], first);
assert.equal(session.queue.length, 8);
assert.equal(data.cards[first].level, 0);
const second = session.queue[0];
rateCard(data, "word", "vague", now);
assert.equal(session.queue[4], second);
const loaded = parseProgress(JSON.stringify(data));
assert.deepEqual(ensureSession(loaded, deck, "word", now), session);
while (session.queue.length) rateCard(data, "word", "known", now);
assert.equal(data.history[dayKey(now)].completed.length, 8);
assert.equal(ensureSession(data, deck, "word", now).queue.length, 0);
session = ensureSession(data, deck, "word", new Date("2026-09-06T08:30:00+08:00"));
assert.equal(session.queue.length, 16);
assert(session.queue.slice(0, 8).every(id => data.cards[id]));
rateCard(data, "word", "known", new Date("2026-09-06T08:30:00+08:00"));
assert.equal(data.cards[first].level, 2);
assert.equal(dayKey(new Date(data.cards[first].due)), "2026-09-09");
assert.equal(ensureSession(data, deck, "sentence", now).queue.length, 2);
const singleton = emptyProgress();
ensureSession(singleton, deck.slice(0, 1), "word", now);
rateCard(singleton, "word", "forgot", now);
assert.equal(singleton.sessions.word.queue.length, 1);
rateCard(singleton, "word", "known", now);
assert.equal(singleton.sessions.word.queue.length, 0);
assert.throws(() => parseProgress('{"version":3}'));
assert.throws(() => parseProgress("invalid json"));
const old = emptyProgress();
delete old.stats;
old.cards[first] = {level: 2, due: now.getTime(), lastGrade: "known"};
const migrated = parseProgress(JSON.stringify(old));
assert.equal(migrated.cards[first].level, 2);
assert.equal(migrated.stats[first].partial, true);
assert.equal(migrated.stats[first].known, 0);
assert.equal(data.stats[first].known, 2);
console.log(`Review checks passed: ${deck.filter(card => card.type === "word").length} words, ${deck.filter(card => card.type === "sentence").length} sentences; persistence, repetition, daily rollover, intervals, deduplication.`);
